ifndef::imagesdir[:imagesdir: ../images]

[[section-system-scope-and-context]]
== System Scope and Context


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.




****



[plantuml, format=png]
....
title Business Context
left to right direction


actor user as "Player"
rectangle STAP as "STAP System"  
cloud Wikidata as "Wikidata API"

user -- STAP
STAP -- Wikidata
....

* *Player* (user): The user interacts with the STAP web application using the front-end of the application.
* *STAP System* (core system): System that allows the players to play question games based on information from the wikidata api
* *Wikidata API* (external system): Api which exposes the information stored in wikidata database

=== Technical Context

[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

.Table of the Technical Context
[cols="2,2", options="header"]
|===
| **Component** | **Technologies Used**
| Front-end      | HTML, CSS (Tailwind), JavaScript (React)
| Backend       | node.js (Express), Wikidata's API
| Database  | MongoDB
| Arquitechture | Microservices
| Deployment and Maintenance | Docker
|===


.Diagram of the Technical Context
[plantuml, format="png"]
----
@startuml
title Technical Context
left to right direction


' Define components as rectangles without default stereotypes
actor "User" as User
rectangle "WebApp" as WebApp
rectangle "Gateway" as Gateway
rectangle "User Service" as Users
database "Database" as Db
rectangle "Wikidata Service" as WikidataService
cloud "Wikidata" as Wikidata


' Define connections
User --> WebApp :http
WebApp --> Gateway
Gateway --> Users :axios
Users --> Db :mongoose
Gateway --> WikidataService :axios
WikidataService --> Wikidata

@enduml
----


.Mapping Input/Output to Channels
[cols="2,2", options="header"]
|===
| **Component** | **Functionality**
| Front-end | User interaction and results display.
| Backend | Logical processing, communication with external API and database.
| Database | Data storage.
| External API | Data query from Wikidata.
|===

In this flow:
- The user interacts with the user interface (front-end) through clicks and responses.
- The Backend processes the requests, consults the Wikidata API, and updates the screen.
- The channels are the HTTP connections between the components.
- The mapping evaluates the user’s responses in real time to provide an appropriate response. 