ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

Our project is configurated using GitHub actions in such a way that every release that is made will trigger some unitary and end to end test, and an attempt to deploy the application over a server.
This will allow our team to achieve continuous deployment and delivery.

=== Quick deployment guide

Using your Azure account:

* Create an Ubuntu-20.04 virtual machine from Azure link:https://www.portal.azure.com[www.portal.azure.com]
** Select an available location (usually Switzerland North, Zone 1, is available)
** Select the virtual machine "Standard B1s (1 vcpu, 1GiB of memory)"
** Set the username to `azureuser`
** Allow SSH on port 22

* Configure GitHub repository secrets with the server's information:
** Download the private key (.pem file) and paste all of its textual content over `DEPLOY_KEY`. Save the file for later configurations over SSH at the virtual machine.
** Check the public IP at Azure and paste it over `DEPLOY_HOST`.
** `DEPLOY_USER` does not need to be changed

* Once the virtual machine is created and the repository is configured, go to Network Settings and add extra rules:
** Open port number 3000 for user services
** Open port number 8000 for accessing the web application
*** More services will be available in the future, so discussions will be made for additional ports supporting our services.

* Configure the virtual machine connecting through SSH for using Docker:
** Use some tool for connecting to the server using SSH (PuTTY, MobaXterm...)
** Use the public IP address and the local .pem file for making the connection.
** Run the following commands for preparing the virtual machine:

+
[listing]
----
sudo apt update
----

+
[listing]
----
sudo apt install apt-transport-https ca-certificates curl software-properties-common
----

+
[listing]
----
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
----

+
[listing]
----
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
----

+
[listing]
----
sudo apt update
----

+
[listing]
----
sudo apt install docker-ce
----

+
[listing]
----
sudo usermod -aG docker ${USER}
----

+
[listing]
----
sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
----

+
[listing]
----
sudo chmod +x /usr/local/bin/docker-compose
----

* Make a release in GitHub:
** On the right-hand side of the main Code section of our repository, there is a section called Releases. It will be needed to add a new version following the version naming convention.
** Once the release is made, some GitHub actions will be triggered, and the containers will be tested and running once everything finishes.
** If some test fails during the process, deployment will be automatically aborted.


=== Infrastructure
General view of system's infrastructure
[plantuml, target=deployment-diagram, format=png]
....
actor client as "Client"
frame UbuntuServer {
    frame Docker {


        frame WebAPP {
            node React
        }

        frame NodeJSGateway {
            node Authentication

            node Users
        }

        frame MongoDB {
            node UsersDatabase

            node ResultsDatabase
        }

        frame .NET {
            node RestAPI
        }
    }

    frame GitHub{

        frame GitHubActions{
            node dockerCompose
        }

    }
}

.NET -- ResultsDatabase : MongoDB (port 27017)
NodeJSGateway -- UsersDatabase : MongoDB (port 27017)
WebAPP -- NodeJSGateway : (port 8000:8002)
WebAPP -- .NET : .NET (port TBD)
client -- WebAPP : Web Browser (port 3000)

Docker -- GitHubActions : on release
....


=== Infrastructure Level 1 - Azure Ubuntu Server

The Ubuntu server allows us to have a isolated machine with the minimal required configuration and installations for running our services.
Having our server on Azure, allows us to minimize the costs of having that machine running, as well as to avoid taking care of some responsabilities such as security, availability or maintainance.


=== Infrastructure Level 2 - Docker

Instead of having a virtual machine for running the whole application by itself, the application is splitted into different services that can be completely isolated.
Docker allows us to create containers with the minimum amount of resources needed for running that specific service, such that resources are not wasted and services that could be more used do not collapse others. Each container contains the specific docker image for running the specific service.
Each implemented service will be isolated at deploy time, so there is no need of making the services at the same programming language or following the same architectural patterns, and responses will be responded through different independent endpoints.

The virtual machine will contain as many containers as services in the application.

For now, the project contains:
** Web application service running on port 3000
*** Gateway (middleware) service running on port 8000
*** Users and authentication services running on ports 8001 and 8002 respectively
** Mongo DB server running on port 27017
** Prometheus running on port 9090 for monitoring
** Grafana running on port 9091 for analytics and monitoring


=== Infrastructure Level 3 - GitHub actions

GitHub actions will provide us with continuous automatic delivery and integration, automating the deployment phase at each release.


[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_

Motivation::

_<explanation in text form>_

Quality and/or Performance Features::

_<explanation in text form>_

Mapping of Building Blocks to Infrastructure::
_<description of the mapping>_


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_


