name: Deploy on release

on:
  release:
    types: [published]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - run: npm --prefix gatewayservice ci
    - run: npm --prefix webapp ci
    - run: npm --prefix wikidataservice ci
    - run: npm --prefix users ci
    
    - run: npm --prefix gatewayservice test -- --coverage
    - run: npm --prefix webapp test -- --coverage
    - run: npm --prefix wikidataservice test -- --coverage
    - run: npm --prefix users test -- --coverage
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  e2e-tests:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm --prefix wikidataservice install
    - run: npm --prefix users install
    - run: npm --prefix gatewayservice install
    - run: npm --prefix webapp install
    - run: CI=false npm --prefix webapp run build CI=true
    - run: npm --prefix webapp run test:e2e

  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Setup certificate
      run: |
        mkdir -p webapp/certificate
        echo -e "${{ secrets.CERTIFICATE }}" > webapp/certificate/certificate.crt
        echo -e "${{ secrets.CERTIFICATE_KEY }}" > webapp/certificate/certificatekey.key
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_URI: https://${{ secrets.DEPLOY_HOST }}:8000
      with:
          name: arquisoft/wiq_en3a/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: |
            API_URI
  docker-push-users:
    name: Push users API Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
          name: arquisoft/wiq_en3a/users
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: users
  docker-push-wikidataservice:
    name: Push wikidata API Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
          name: arquisoft/wiq_en3a/wikidataservice
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: wikidataservice
  docker-push-gatewayservice:
    name: Push gateway service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    steps:
    - uses: actions/checkout@v4
    - name: Setup certificate
      run: |
        mkdir -p gatewayservice/certificate
        echo -e "${{ secrets.CERTIFICATE }}" > gatewayservice/certificate/certificate.crt
        echo -e "${{ secrets.CERTIFICATE_KEY }}" > gatewayservice/certificate/certificatekey.key
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        WEBAPP_URI: https://${{ secrets.DEPLOY_HOST }}:443
        GATEWAY_URI: https://${{ secrets.DEPLOY_HOST }}:8000
      with:
        name: arquisoft/wiq_en3a/gatewayservice
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        workdir: gatewayservice
        buildargs: WEBAPP_URI, GATEWAY_URI

  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-gatewayservice, docker-push-webapp, docker-push-users, docker-push-wikidataservice]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          wget https://raw.githubusercontent.com/arquisoft/wiq_en3a/master/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/arquisoft/wiq_en3a/master/.env
          git clone https://github.com/Arquisoft/wiq_en3a.git
          mv ./wiq_en3a/gatewayservice .
          docker compose --profile prod down
          docker compose --profile prod up -d --pull always
